### ISSUE TITLE
Ensure all directives using uif-type attribute have test cases to verify the binding of scope variables work

### ISSUE THREAD

**Issue by andikrueger** [ngOfficeUIFabric/ng-officeuifabric#358]
Some directives use the uif-type attribute to bind a string or a scope property into the directive's scope. As discussed in #356: a change of the scope property or string is reflected in our directives.

We should check our directives whether the binding of uif-type attribute should be watched and tested to confirm uif-type binds and watches scope variables correctly.

What is this good for? For example: The message bar shows a default message to the user. After the field got validated the message bar should change into an error message. If uif-type is not watched properly, changes of the type aren’t reflected in the directive.

The following directives that are checked off have either been fixed or confirmed this isn't something to address with them. If they are unchecked, that means investigation is still required.
- [x] uif-button (NA... see https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/358#issuecomment-235257889)
- [x] uif-callout
- [x] uif-choicefield (ref #445, fixed in #448)
- [x] uif-dialog (NA... see https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/358#issuecomment-267578992)
- [x] uif-icon (ref #443, fixed in ~~#398~~ #444)
- [x] uif-list-item (ref #446, fixed in #452)
- [x] uif-message-bar (ref #356, fixed in #357)
- [x] uif-panel (NA... see https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/358#issuecomment-267578992)
- [x] uif-people-picker (ref #447, NA... see https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/447#issuecomment-267759873)
- [x] uif-pivot
- [x] uif-texfield (ref #440, fixed in #441)

**Comment by andrewconnell** [comment]
`uif-button` isn't necessary to check... while we could add code to monitor changes, it doesn't make sense as the case of changing a button from one type to another (primary, compound, command, hero) isn't a use case we need to support.

**Comment by andrewconnell** [comment]
Revisiting this issue... I'm in bug squashing mode!

My take is that for directives where it makes sense, they should monitor changes to the `uif-type` attribute and re-render the directive accordingly. For instance, if a `uif-textfield` changes from a *text* to an *email* type, the control should get updated... right?

While I see some of these items have been addressed, I don't see a single one working the way we have specifying in this issue. Is anyone else? I'm trying to find one that works the way we want it to work, but I don't see any. Even though the `uif-messagebar` shows it was fixed by @jjczopek in #357, it doesn't seem to change... so it's not really fixed... right? When I update the tests to have it render once, then modify the bound scope property to something else, I'm not seeing it change.

I've been working on the text field directive to get a good pattern set, but so far I can't catch anything when the `uif-type` attribute changes, even using the `$watch` function like outlined in this SO post: http://stackoverflow.com/questions/20068526/angularjs-directive-does-not-update-on-scope-variable-changes

Input?

**Comment by sjclemmy** [comment]
I just had a play with the `uif-messagebar`, manually and the $watch on `uifType`worked correctly.
It does depend on the value being supplied as an angular expression. e.g. `uif-type="{{vm.myType}}"`

**Comment by andrewconnell** [comment]
Maybe that's my issue then... let me have another play with it... how do you verify it with a test? In the current tests for `uif-messagebar`, it doesn't change the value on the scope within a test from one value to another. This is how I was doing it with `uif-textfield`... would this not be correct?

```
it(
  'should allow to interpolate uif-type value',
  inject((
    $compile: angular.ICompileService,
    $rootScope: angular.IRootScopeService,
    $log: angular.ILogService) => {

    let inputElement: JQuery = null;
    let scope: any = $rootScope.$new();
    let html: string = `<uif-textfield uif-label='some label' uif-type='{{type}}'></uif-textfield>`;
    let element: JQuery = angular.element(html);

    scope.type = 'password';

    // compile with scope = password
    $compile(element)(scope);
    scope.$digest();
    element = jQuery(element[0]);

    // test that password is listed
    inputElement = element.find('input');
    expect(inputElement.attr('type')).toBe('password');


    // change scope
    scope.type = 'number';

    // compile with scope = number
    $compile(element)(scope);
    scope.$digest();
    element = jQuery(element[0]);

    // test that password is listed
    inputElement = element.find('input');
    expect(inputElement.attr('type')).toBe('number');
  })
);
```

In that test, the first `expect()` passes, but not the second as the value of the type attribute did not change even though the scope changed.

**Comment by sjclemmy** [comment]
uifType is not bound to the scope in the textFieldDirective. That is the issue.
```
  public scope: {} = {
    max: '@',
    min: '@',
    ngChange: '=?',
    ngModel: '=?',
    placeholder: '@',
    step: '@',
    uifDescription: '@',
    uifLabel: '@'
  };
```
Explicitly it needs `uifType: '@'` adding to it.

**Comment by andrewconnell** [comment]
Not in the code that's currently in the repo, but in my local fork it does... at this point trying to make sure I have a test that can reflect what SHOULD be happening.

**Comment by sjclemmy** [comment]
I see it now. There are two issues:
1. You are assigning `element` after the first compile : `element = jQuery(element[0]);`  and then recompiling using this, so it's not the same content. Setting `element = angular.element(html);` before the second `$compile` will fix it.
2. You don't need to recompile it anyway. You just need a $digest loop. Remove the second `$compile(element)(scope);`

Actually I'll change that to, you SHOULDN'T recompile, because it's only compiling once in production, but continually running `$digest`, so the test is not representative of the actual behaviour if it's re-compiled.

**Comment by andrewconnell** [comment]
IMHO it does not make sense to change the type of a dialog on the fly given the options we support (none, header, multiline), thus removing that from the list.

Same is true for a panel.
